language: scala
jdk:
  - oraclejdk8
script:
  - sbt clean test  
# script:
#  - sbt clean coverage test
# after_success:
#  -sbt coverageReport coveralls
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
